#!/usr/bin/env bash

SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )

echo "Get latest"
pushd $BC_INSTALL_DIR
git pull
popd

if ! command_exists wget; then
    echo "Error: wget not installed. Please add." >&2
    exit 1
fi

# update
if [ "$1" == "-u" ]; then
    pushd $BC_INSTALL_DIR

    pushd completion
    wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -O git.completion.bash
    popd

    popd
fi
