#!/bin/sh

CHLOC="$BC_INSTALL_DIR/.cheat"

# -e : edit
if [ "$1" = "-e" ]; then
  if [ ! -d "$CHLOC" ]; then
    git clone http:// $CHLOC
  fi
  $EDITOR $CHLOC
  exit 0
fi

SHEET=
if [ ! -z $1 ]; then
  
  if [ "$1" = "-l" ]; then
    pushd $CHLOC/sheets
    ls *.md
    popd
    exit 0
  fi
  
  if [ ! -e "$CHLOC/sheets/$1.md" ]; then
    echo "Unknown cheatsheet: $1"
    exit 1
  fi
  
  SHEET="?sheet=$1";
fi

URL="file://$CHLOC/index.html${SHEET}"

case `uname -s` in
Darwin)
  exec osascript <<EOM
    on run argv
    tell application "Safari" to open location "${URL}"
    end run
EOM
;;
CYG*) open $URL ;;
esac
