#!/usr/bin/env bash

ADDED=

if [ ! -d '.git' ]; then
    git init
fi

if [ ! -f '.gitattributes' ]; then
    cat << NEWGIT_EOM > .gitattributes
* text=auto

NEWGIT_EOM
    git add .gitattributes
    ADDED=1
fi

if [ ! -f '.gitignore' ]; then
cat << NEWGIT_EOM > .gitignore

build*/

*.py[cod]
__pycache__/

NEWGIT_EOM
    git add .gitignore
    ADDED=1
fi

if [ ! -z $ADDED ]; then
    git commit -m 'Add git config'
    git log
fi
