#!/usr/bin/env bash

FNAME="$1"

if [ -z "$FNAME" ]; then
    echo "No name given"
    exit 1
fi

if [ -e "$FNAME" ]; then
    echo "Script already exists"
    exit 1
fi

cat << 'EOF' >> "$FNAME"
#!/usr/bin/env bash

SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )

FILE=$1
OUT=${FILE%.*}_.mp4

usage() {
  echo "Usage: $0 [-i] [-c] VIDEO"
}

# getopt "x" no-arg, "x:" required arg, "x::" optional arg
while getopts "ic" OPT; do
  case "${OPT}" in
    i)
      echo "$FILE"
      shift
      ;;
    c)
      blah
      shift
      ;;
    *) usage ;;
  esac
done

shift "$((OPTIND-1))"

ARGS=$@

EOF

chmod u+x "$FNAME"
