#!/usr/bin/env bash
# Android application support for Unity
# 	= config files in ~ & .
# 	- Captures log.
# ADB docs: https://developer.android.com/studio/command-line/adb

CONFIGFILE=.uadb
LOGFILE=adblog.txt
BUILDLOG=Build.log # Unity build output log
UNITY_ADB_PATH=Editor/Data/PlaybackEngines/AndroidPlayer/SDK/platform-tools/adb
ADB_HOW=Unset

# package.apk path
APK=
# com.vendor.app package name
PACKAGE=
# path of adb to use
ADB=
# activity to run the package
ACTIVITY=
# logcat filter
LOGOPTS=all
# VR platform
VRPLATFORM=
VRSUPPORTED='ovr|wave'


usage () {
	colecho -white "  $(basename $0) [-hbsiulrc] [PACKAGE.apk]"
	cat <<EOM
 
	-h          help
	-p          platform [$VRSUPPORTED]
	-i [APK]    install package to device
	-u PKG      uninstall package from device
	-r PKG      run package app on device
	-l [OPTS]   capture app log output in $LOGFILE
	              all   show all output
	-c CMDS     call ADB with the given commands

	--list      list installed packages
	--dump      dump installed package info
	--act       get run activity for package

	--bare      start Baretail following the log
	--side      use SideQuest ADB

	e.g. run & log:	uadb -r -l

	ADB docs: https://developer.android.com/studio/command-line/adb
EOM
}

if [ ! -f ~/$CONFIGFILE ]; then
	cat > ~/$CONFIGFILE <<EOM
# uadb config file - change these values as appropriate for your environment

# Where Unity installs go
#UNITY_INSTALL=/cygdrive/c/Unity

# Default Unity version to use
#UNITY_PATH=$UNITY_INSTALL/2019.4.25f1

# Global ADB path to use.
#ADB=
EOM
fi

if [ ! -f ./$CONFIGFILE ]; then
	cat > ./$CONFIGFILE <<EOM
# uadb config file - change these values as appropriate for your environment

# Unity install to use
#UNITY_PATH=$UNITY_INSTALL/2019.4.25f1

# ADB path to use. If blank & UNITY_PATH set, uses Unity adb.
#ADB=

#APK=
#PACKAGE=

ACTIVITY_ovr=com.unity3d.player.UnityPlayerActivity
ACTIVITY_wave=com.htc.vr.unity.WVRUnityVRActivity
ACTIVITY=$ACTIVITY_ovr  # default

LOGOPTS_ovr="Unity:V OVRPlatform:D *:S"
LOGOPTS_wave="Unity:V VRCORE:D *:S"
LOGOPTS=$LOGOPTS_ovr  # default
EOM
fi

source ~/$CONFIGFILE
source ./$CONFIGFILE

ADB=$ADB_PATH
ADB_HOW="From $CONFIGFILE config"

# Work out path to adb
if [ -z $ADB ]; then
	#colecho -cyan "ADB_PATH unset. Trying to determine path."
	if [ -z $UNITY_PATH ]; then
		colecho -red "UNITY_PATH not set in $CONFIGFILE config"
	else
		if [ ! -d $UNITY_PATH ]; then
			colecho -red "No Unity install at UNITY_PATH=$UNITY_PATH"
			exit 1
		fi
		if [ -x $UNITY_PATH/$UNITY_ADB_PATH ]; then
			ADB=$UNITY_PATH/$UNITY_ADB_PATH
			ADB_HOW="From Unity: $UNITY_PATH"
		fi
	fi

	if [ -z $ADB ]; then
		if [ -f $BUILDLOG ]; then
			# Find the adb path specified in the log and get the path.
			# Also strip off Windows CR line ending \r
			LOG_ADB=$(grep '^\sadb' $BUILDLOG | sed 's/adb\s*:\s*//' | sed 's/\r//')
			if [ ! -z $LOG_ADB ]; then
				ADB=$(cygpath -u "$LOG_ADB")
				ADB_HOW="From $BUILDLOG"
				echo "adb found in $BUILDLOG: $ADB"
			else
				echo "adb not found in $BUILDLOG"
			fi
		fi
	fi
fi

if [ -z $ADB ]; then
	colecho -red "Error: could not find ADB in $CONFIGFILE or $BUILDLOG"
	exit 1
fi

function get_package ()
{
	local PKG=${1/.apk/}  # strip postfix
	if [ -z $PKG ] || [ ! -f $PKG.apk ]; then
		echo "Error: Package $PCK.apk not found" >&2
	fi
	echo $PKG
}

while [ $# -ne 0 ]; do
	case "$1" in
	-h|--help)
		usage
		echo
		colecho -yellow "    UNITY_INSTALL=" -grey "${UNITY_INSTALL:-"*unset*"}"
		colecho -yellow "    UNITY_PATH=" -grey "${UNITY_PATH:-"*unset*"}"
		colecho -yellow "    ADB=" -grey "${ADB:-"*not found*"}"
		colecho -yellow "    Adb found: " -grey "$ADB_HOW"
		colecho -yellow "    APK=" -grey "${APK:-"*unset*"}"
		colecho -yellow "    PACKAGE=" -grey "${PACKAGE:-"*unset*"}"
		colecho -yellow "    ACTIVITY=" -grey "${ACTIVITY:-"*unset*"}"
		shift
		;;
	-p|--platform)
		shift
		if [[ "|$VRSUPPORTED|" =~ "|$1|" ]]; then
			VRPLATFORM=$1
			ACTIVITY=ACTIVITY_$VRPLATFORM; ACTIVITY=${!ACTIVITY}
			LOGOPTS=LOGOPTS_$VRPLATFORM; LOGOPTS=${!LOGOPTS}
		else
			colecho -red "Unrecognised platform: $1"
			exit 1
		fi
		shift
		;;
	-i|--install)
		$ADB devices
		PKG=$APK
		if [ -z $PKG ] || [ ! -f $PKG ]; then
			colecho -red "Error: Package $PKG not found" >&2
		fi
		echo "Stopping $PACKAGE"
		$ADB shell am force-stop $PACKAGE
		echo "Installing $PKG"
		$ADB install -r $PKG
		shift
		;;
	-u|--uninstall)
		echo "Stopping $PACKAGE"
		$ADB shell am force-stop $PACKAGE
		echo "Uninstalling $PACKAGE..."
		$ADB uninstall $PACKAGE
		shift
		;;
	-r|--run)
		colecho -purple "Running $ACTIVITY..."
		echo "Stopping existing package"
		$ADB shell am force-stop $PACKAGE
		sleep 1
		echo "Starting new instance of package"
		$ADB shell am start -a $ACTIVITY
		shift
		;;
	--list)
		# show 3rd party packages installed
		colecho -yellow "Packages"
		$ADB shell pm list packages -3
		shift
		;;
	--dump)
		# dump all package info
		$ADB shell pm dump $PACKAGE
		shift
		;;
	--act)
		colecho -yellow "Activity in installed package $PACKAGE:"
		# Get the launcher activity https://stackoverflow.com/a/41325792/3233
		$ADB shell "cmd package resolve-activity --brief $PACKAGE | tail -n 1"
		shift
		;;
	-c|--cmd)
		# user command
		shift
		$ADB $*
		break
		;;
	-l|--log)
		shift
		OPTS="$LOGOPTS"
		while [ $# -ne 0 ]; do
			case $1 in
			all) OPTS="" ;; # no filters
			-*) break ;;
			*) OPTS="$OPTS $1"
			esac
			shift
		done
		echo "Capture log ($OPTS)"
		$ADB logcat "$OPTS" > $LOGFILE
		;;
	--side)
	  	ADB=$(cygpath -u "$HOMEPATH\AppData\Roaming\SideQuest\platform-tools\adb.exe")
		echo "Use SideQuest ADB"
		shift
		;;
	--bare)	
		if ! $(command_exists baretail); then
			colecho -red "Error: Baretail is not in the path."
			exit 1
		fi
		echo "Starting Baretail..."
		exec baretail $(cygpath -w $LOGFILE) &  # https://baremetalsoft.com/baretail/
		shift
		;;
	*) 	
		colecho -red "Unknown option: $1" >&2
	  	exit 2
	  	;;
	esac
done
